### PR TITLE
Minor fixes to 1.8.1

### PR DESCRIPTION
**Pull request by Silari**
Adds Space Exploration support to allow building on space platforms per [this request](https://mods.factorio.com/mod/creative-mod/discussion/63edf4a6d0dfa2d615c0fbd8)

Adds a setting to change who can set Infinity Chest filters per [this request](https://mods.factorio.com/mod/creative-mod/discussion/6549d7c94e0f0561e69a8c19)

Updated the event menus to include new events and categorize some old ones that weren't per [this report](https://mods.factorio.com/mod/creative-mod/discussion/649b30013ae07eab43b03d5a)

Fixed a bug logging parameters when mining an item on the ground per [this report](https://mods.factorio.com/mod/creative-mod/discussion/649b56370bcefee45dad63ce)

### CODE REVIEW

**Review by jodli — CHANGES_REQUESTED** [review]
Can you rework this commit (26f52710d340c8507c73ebb8785e9f644bb095d3) to only contain the changes you made?

It seems like you touched the whole file maybe due to some encoding or line ending change?

**Comment by jodli** [comment]
Thank you for your pull request. I am currently busy and may not be able to keep up with issues and discussions for this mod.
I have reviewed your changes, and they look good to me.

Once you have fixed the one commit (26f52710d340c8507c73ebb8785e9f644bb095d3), I will merge the PR and create a new release.

By the way, would you like to collaborate further on this mod? If so, you can contact me at jobst87@gmail.com.

**Comment by Silari** [comment]
Not sure why it's doing that - it's normal if the 'hide whitespace changes' option is enabled, but even reverting back to the original file with no changes it still shows the whitespace changes. If you have an idea on how to fix it I'd be thankful but nothing I try seems to work.

**Comment by jodli** [comment]
I've merged it manually in 1646fd3dc792c5688a2781f4cf070e6afcfed2e0. Not sure what happened to your `events.lua` file 😝 

Thank you so much for the contribution!

**Pull request closed without merging**
